config/routes.rb
Rails.application.routes.draw do
  resources :patients
  get 'home/about'
  #root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:PID, :f_name, :l_name, :NIC, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'WebTest', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">


        <%= link_to "Patients", patients_path, class:"nav-link" %>
        <%= link_to "Add Patient", new_patient_path, class:"nav-link" %>
        <%= link_to "About Us", home_about_path, class:"nav-link" %>



      </div>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>WebTest</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WebTest</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>
  <body>

    <%= render 'home/header' %>


    <div class="container">
      <br>
    <%= yield %>
    </div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div  class="field form-group">
    <%= form.label :PID, style: "display: block" %>
    <%= form.text_field :PID, class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :First_Name, style: "display: block" %>
    <%= form.text_field :f_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :Last_name, style: "display: block" %>
    <%= form.text_field :l_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :NIC, style: "display: block" %>
    <%= form.text_field :NIC, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :Phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>
<br>
  <div>
    <%= form.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>" class="jumbotron">
  <h1 class="display-4"><%= patient.f_name %> <%= patient.l_name %></h1>
  <hr class="my-4">

</div>


<div id="<%= dom_id patient %>">
  <p>
    <strong>Pid:</strong>
    <%= patient.PID %>
  </p>


  <p>
    <strong>Nic:</strong>
    <%= patient.NIC %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= patient.phone %>
  </p>

</div>

app/views/patients/edit.html.erb
<h1>Edit Patient Details</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Edit this patient", edit_patient_path(@patient), class:"btn btn-secondary" %>
    <%= link_to "Back to patients", patients_path, class:"btn btn-dark" %>

</div>

app/views/patients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Patients List</h1>


<div id="patients">

<table class="table table-striped table-hover">
  <thead class="table table-dark">
  <tr>
    <th>PID</th>
    <th>F Name</th>
    <th>L Name</th>
    <th>NIC</th>
    <th>Phone</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody >
  <% @patients.each do |patient| %>
    <tr>
      <td><%= patient.PID %></td>
      <td><%= patient.f_name %></td>
      <td><%= patient.l_name %></td>
      <td><%= patient.NIC %></td>
      <td><%= patient.phone %></td>
      <td><%= link_to "Show", patient %></td>
      <td><%= link_to 'Edit', edit_patient_path(patient) %></td>

    </tr>
  <% end %>
  </tbody>
</table>


</div>


<%= link_to "New patient", new_patient_path, class:"btn btn-secondary" %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path, class:"btn btn-dark" %>
</div>

app/views/patients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @patient %>

<div>
  <br>
  <%= link_to "Edit this patient", edit_patient_path(@patient), class:"btn btn-secondary" %>
    <%= link_to "Back to patients", patients_path, class:"btn btn-dark" %>
  <br><br>

  <%= button_to "Delete this patient", @patient, method: :delete ,  class:"btn btn-danger"%>

</div>